### ISSUE TITLE
Add Makefile target to make a test release

### ISSUE THREAD

**Issue by rm--** [transcode-de/durga#15]
It would be good, to have a test to be sure to have all together to start an new release.

**Comment by keimlink** [comment]
What do you exactly want to test before releasing?

**Comment by rm--** [comment]
I would like to test if all tests are running for all environments (py27, py34, pypy, ....) and that no file in MANIFEST is missing (see issue #14 ).

Addtionally before upload new package to PYPI the [test instance of PYPI](https://testpypi.python.org/pypi) could be used.

**Comment by keimlink** [comment]
Because we already have a target for testing with tox (which will also check the MANIFEST after #14 has been resolved) we only need a target to upload to testpypi. So please revise the issue's title accordingly.

Then we could use `make test-all dist test-upload` to test, build and upload to testpypi.

**Comment by rm--** [comment]
Okay, so I will add an `test-upload` target to Makefile for uploading to testpypi. After that it should be possible to run your mentioned command chain.
